### ISSUE TITLE
Reproducing plots in the paper

### ISSUE THREAD

**Issue by kgarg8** [dylan-slack/fairness-warnings-fair-maml#9]
Hi Dylan,

Thanks for open-sourcing the code for the paper.

I tried to reproduce the results/ plots. Particularly I am interested in the plot in Figure 3 in the paper which shows FAIR-MAML accuracy vs dp plot. I feel that some of the details are missing in plotting the same curve.

The below are the values that I got after 2000 epochs for different gamma values.
These values suggest accuracy around 0.40 whereas the lowest accuracy for FAIR-MAML is ~0.55.
Can you elaborate more on your procedure to plot the curve?

GAMMA 0
Avg tuning Acc: [0.4236 0.7734 0.725  0.7324 0.801  0.7593]
Avg tuning DP: [   inf 0.4766 0.3982 0.406  0.445  0.4102]

GAMMA 4
Avg tuning Acc: [0.407  0.7466 0.773  0.72   0.6997 0.7   ]
Avg tuning DP: [   inf 0.6685 0.6816 0.7666 0.7915 0.8027]

GAMMA 5
Avg tuning Acc: [0.43   0.694  0.674  0.6504 0.6836 0.663 ]
Avg tuning DP: [   inf 0.6626 0.608  0.628  0.653  0.653 ]

GAMMA 6 
Avg tuning Acc: [0.3113 0.584  0.567  0.607  0.607  0.647 ]
Avg tuning DP: [   inf 0.663  0.9766 0.7764 0.7764 0.7764]

Thanks,
Krishna

**Comment by dylan-slack** [comment]
Hi Krishna,

Thanks for checking out the code :)

What you're seeing here is the fine-tuning.  Perhaps this could be clarified in the code a bit, you're right.  The 0th spot in each list is the meta-model with "0-steps" of optimization.  However, as you give it a couple instances of the fine-tuning set and an epoch or two of optimization (the following instances in each list) you see it quickly adapts and gets pretty good accuracy / dp trade offs rapidly (recall this is only done on a very small number of fine-tuning instances).

**Comment by kgarg8** [comment]
Dylan,
Thanks for the response.

Correct what you are saying. However, I was looking for an explanation about the procedure to get this blue line curve from the experimental values.


![Screen Shot 2020-06-11 at 5 27 55 PM](https://user-images.githubusercontent.com/30385849/84445280-34476a00-ac09-11ea-98c0-5b326322a00d.png)

**Comment by dylan-slack** [comment]
We fix a step size (we choose 1 epoch of fine tuning per the paper) and then plot this trade off over a couple initializations.  Interestingly, the example you've provided here looks reasonable in terms of accuracy, but the DP doesn't look that great to me.  Can I ask if you've modified any parameters?
